import { Injectable, NotFoundException, OnApplicationBootstrap } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { v4 as uuidv4 } from 'uuid';
import { CourseOrmEntity } from '../../persistence/postgres/entities/course.orm.entity';
import { UserProgressOrmEntity } from '../../persistence/postgres/entities/user-progress.orm.entity';
import { QuizResultOrmEntity } from '../../persistence/postgres/entities/quiz-result.orm.entity';
import { UpdateProgressDto } from '../dtos/update-progress.dto';

/* ─────────────── INSTRUCTORS ─────────────── */
const INSTRUCTORS = {
  CM: { name: 'Carlos Mendoza', role: 'Consultor en Transformación Digital', initials: 'CM' },
  LF: { name: 'Laura Fernández', role: 'Coach Ejecutiva & Especialista en Liderazgo', initials: 'LF' },
  AC: { name: 'Ana Caro Corbelle', role: 'HR Leader & Especialista en Marca Personal', initials: 'AC' },
  RS: { name: 'Roberto Silva', role: 'Experto en Productividad y Gestión del Cambio', initials: 'RS' },
  MT: { name: 'María José Torres', role: 'Especialista en Innovación y Creatividad', initials: 'MT' },
};

/* ─────────────── LESSONS PER COURSE ─────────────── */
const COURSE_LESSONS: Record<string, any[]> = {
  'Fundamentos de Inteligencia Artificial': [
    { id: 1, title: '¿Qué es la IA y por qué importa hoy?', type: 'Video', duration: '12:30', description: 'Introducción a la inteligencia artificial: historia, conceptos clave y por qué es relevante para tu carrera.', noteIntro: 'La IA ya está en tu vida: en el correo que filtra spam, en las recomendaciones de Netflix, en los asistentes de voz. Entender cómo funciona te da ventaja en cualquier industria.', notes: [{ bold: 'IA vs ML vs Deep Learning:', text: ' IA es el concepto amplio; ML son los algoritmos que aprenden de datos; DL son redes neuronales profundas.' }, { bold: 'IA estrecha vs general:', text: ' Toda la IA actual es estrecha — muy buena en una tarea. La IA general (como en las películas) no existe aún.' }, { bold: 'Por qué ahora:', text: ' Tres factores convergieron: datos masivos, cómputo barato en la nube y algoritmos mejorados.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Glosario de IA para profesionales', type: 'PDF', size: '0.6 MB' }, { name: 'Mapa: ecosistema de IA', type: 'PDF', size: '0.4 MB' }] },
    { id: 2, title: 'Machine Learning en la práctica', type: 'Video', duration: '15:20', description: 'Cómo los algoritmos de ML aprenden de los datos y qué tipos existen.', noteIntro: 'Machine Learning es la rama de la IA que le permite a las máquinas aprender de la experiencia. No necesitás saber programar para entender cómo aprovecharlo.', notes: [{ bold: 'Aprendizaje supervisado:', text: ' El algoritmo aprende de ejemplos etiquetados. Ej: detectar emails spam a partir de miles de ejemplos.' }, { bold: 'Aprendizaje no supervisado:', text: ' Encuentra patrones sin etiquetas. Ej: segmentación de clientes por comportamiento.' }, { bold: 'Herramientas sin código:', text: ' Google AutoML, Teachable Machine y Azure ML permiten crear modelos sin programar.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Cheatsheet de algoritmos ML', type: 'PDF', size: '0.8 MB' }, { name: 'Casos de ML por industria', type: 'PDF', size: '1.1 MB' }] },
    { id: 3, title: 'IA en tu industria: casos reales', type: 'Video', duration: '18:00', description: 'Ejemplos concretos de IA aplicada en RRHH, finanzas, salud, retail y logística.', noteIntro: 'La mejor forma de entender la IA es verla en acción. En esta lección analizamos casos reales de empresas que ya la usan y qué resultados obtuvieron.', notes: [{ bold: 'RRHH:', text: ' Screening de CVs, predicción de rotación, onboarding personalizado.' }, { bold: 'Finanzas:', text: ' Detección de fraude en tiempo real, scoring crediticio, trading algorítmico.' }, { bold: 'Retail:', text: ' Recomendaciones personalizadas, gestión dinámica de precios, predicción de demanda.' }, { bold: 'Tu rol:', text: ' No competís con la IA — competís con personas que saben usar IA. Esa es la diferencia.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Casos de uso de IA por sector', type: 'PDF', size: '1.4 MB' }] },
    { id: 4, title: 'Automatización sin programar', type: 'Video', duration: '14:45', description: 'Herramientas no-code para automatizar tareas repetitivas con IA: Zapier, Make, ChatGPT y más.', noteIntro: 'No necesitás ser programador para automatizar. Hoy existen herramientas visuales que permiten conectar apps y crear flujos automáticos en minutos.', notes: [{ bold: 'Zapier y Make:', text: ' Conectan más de 5.000 aplicaciones. Podés automatizar emails, notificaciones, reportes y más.' }, { bold: 'ChatGPT en el trabajo:', text: ' Redacción, resúmenes, análisis, traducción, código. Usarlo bien es una habilidad diferencial.' }, { bold: 'Notion AI y Copilot:', text: ' IA integrada en herramientas de productividad que ya usás.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Guía de herramientas no-code con IA', type: 'PDF', size: '0.9 MB' }, { name: 'Plantillas de automatización', type: 'Doc', size: 'Google Docs' }] },
    { id: 5, title: 'Reto: Identificá oportunidades de IA en tu trabajo', type: 'Reto', duration: '10 min', description: 'Quiz para evaluar tu comprensión de IA y su aplicación práctica.', noteIntro: 'Es momento de poner a prueba lo aprendido.', notes: [], instructor: INSTRUCTORS.CM, resources: [] },
    { id: 6, title: 'IA ética y futuro del trabajo', type: 'Video', duration: '16:30', description: 'Sesgos algorítmicos, privacidad de datos y cómo preparar tu carrera para el futuro con IA.', noteIntro: 'La IA tiene un poder enorme — y con ese poder vienen responsabilidades. Esta lección cierra el curso con una mirada crítica y constructiva sobre el futuro del trabajo.', notes: [{ bold: 'Sesgos algorítmicos:', text: ' Los algoritmos aprenden de datos históricos que pueden contener prejuicios. Entender esto es clave.' }, { bold: 'Privacidad:', text: ' GDPR y leyes locales regulan el uso de datos. Conocerlas protege a tu empresa y a vos.' }, { bold: 'Habilidades del futuro:', text: ' Pensamiento crítico, creatividad, inteligencia emocional y habilidades digitales son las más demandadas.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Informe: Futuro del trabajo con IA', type: 'PDF', size: '2.1 MB' }] },
  ],

  'Liderazgo en entornos cambiantes': [
    { id: 1, title: 'El liderazgo en el siglo XXI', type: 'Video', duration: '14:00', description: 'Cómo cambió el concepto de liderazgo y qué se espera de un líder moderno.', noteIntro: 'El liderazgo del siglo XXI no se trata de tener todas las respuestas — se trata de hacer las preguntas correctas y crear condiciones para que el equipo florezca.', notes: [{ bold: 'Del jefe al líder:', text: ' El jefe da órdenes; el líder inspira. La autoridad ya no viene del cargo sino de la credibilidad.' }, { bold: 'Liderazgo situacional:', text: ' No hay un estilo único correcto. El mejor líder adapta su enfoque según la madurez del equipo.' }, { bold: 'Liderazgo distribuido:', text: ' Las organizaciones modernas empoderan líderes en todos los niveles, no solo en la cima.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Autoevaluación de liderazgo', type: 'PDF', size: '0.7 MB' }] },
    { id: 2, title: 'Tu estilo de liderazgo', type: 'Video', duration: '16:30', description: 'Descubrí cuál es tu estilo natural y cómo potenciarlo o complementarlo.', noteIntro: 'Todos tenemos un estilo de liderazgo natural. Conocerlo es el primer paso para ser más efectivo — y para saber cuándo necesitás flexibilizarlo.', notes: [{ bold: 'Estilos principales:', text: ' Visionario, coach, afiliativo, democrático, marcapasos y directivo. Cada uno tiene un contexto ideal.' }, { bold: 'Impacto en el clima:', text: ' El estilo del líder explica hasta el 70% del clima laboral de su equipo, según Goleman.' }, { bold: 'Cómo ampliarlo:', text: ' Identificar tu estilo dominante y practicar los complementarios en situaciones de bajo riesgo.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Test: Estilos de liderazgo de Goleman', type: 'PDF', size: '0.5 MB' }] },
    { id: 3, title: 'Inteligencia emocional aplicada', type: 'Video', duration: '20:00', description: 'Las 5 dimensiones de la IE y cómo desarrollarlas para liderar mejor.', noteIntro: 'La inteligencia emocional es el factor que más diferencia a los líderes excelentes de los promedio. No se nace con ella — se desarrolla.', notes: [{ bold: 'Autoconciencia:', text: ' Conocer tus emociones, fortalezas, debilidades y su impacto en otros.' }, { bold: 'Autogestión:', text: ' Controlar impulsos, adaptarse al cambio, mantener integridad bajo presión.' }, { bold: 'Empatía:', text: ' Entender el estado emocional de otros. Base del trabajo en equipo y la negociación.' }, { bold: 'Habilidades sociales:', text: ' Influir, comunicar, gestionar conflictos, inspirar y desarrollar personas.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Guía de desarrollo de IE', type: 'PDF', size: '1.2 MB' }] },
    { id: 4, title: 'Comunicación como líder', type: 'Video', duration: '18:15', description: 'Cómo comunicar visión, dar feedback efectivo y tener conversaciones difíciles.', noteIntro: 'La comunicación es la herramienta principal del liderazgo. Un líder que no sabe comunicar pierde credibilidad, alinea mal y desmotiva sin querer.', notes: [{ bold: 'Comunicación de visión:', text: ' Conectá el trabajo diario con el propósito mayor. ¿Por qué importa lo que hacemos?' }, { bold: 'Feedback SBI:', text: ' Situación → Comportamiento → Impacto. El feedback más objetivo y accionable.' }, { bold: 'Conversaciones difíciles:', text: ' Prepará el contexto, sé directo pero empático, escuchá antes de responder.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Plantilla de feedback SBI', type: 'Doc', size: 'Google Docs' }] },
    { id: 5, title: 'Reto: Tu diagnóstico de liderazgo', type: 'Reto', duration: '15 min', description: 'Quiz de evaluación de liderazgo moderno.', noteIntro: 'Verificá lo aprendido sobre estilos, IE y comunicación de liderazgo.', notes: [], instructor: INSTRUCTORS.LF, resources: [] },
    { id: 6, title: 'Gestión de equipos remotos e híbridos', type: 'Video', duration: '22:00', description: 'Estrategias y herramientas para liderar equipos distribuidos geográficamente.', noteIntro: 'Liderar en remoto amplifica todo — los aciertos y los errores. Requiere más intencionalidad en comunicación, confianza y cultura.', notes: [{ bold: 'Confianza por defecto:', text: ' Los equipos remotos rinden mejor cuando el líder confía sin necesidad de microgestión.' }, { bold: 'Rituales de equipo:', text: ' Daily standup, retros, check-ins 1:1. La frecuencia y calidad de los rituales define la cultura.' }, { bold: 'Herramientas clave:', text: ' Slack, Notion, Loom, Miro, Zoom. Lo importante es la consistencia, no la cantidad.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Kit de liderazgo remoto', type: 'PDF', size: '1.3 MB' }] },
    { id: 7, title: 'Toma de decisiones bajo presión', type: 'Video', duration: '17:45', description: 'Frameworks para decidir rápido y bien cuando hay incertidumbre o urgencia.', noteIntro: 'Los líderes son juzgados por sus decisiones. Desarrollar un proceso sólido y consistente es más valioso que tener "buen instinto".', notes: [{ bold: 'Matriz de decisión:', text: ' Evalúa opciones por criterios ponderados. Elimina el sesgo emocional.' }, { bold: 'Análisis premortem:', text: ' Antes de decidir, imaginá que salió mal. ¿Por qué? Esto revela riesgos ocultos.' }, { bold: 'Decidir con datos incompletos:', text: ' En muchas situaciones urgentes tenés el 70% de la información. Esperando el 100% perdés la ventana.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Framework de toma de decisiones', type: 'PDF', size: '0.6 MB' }] },
    { id: 8, title: 'Reto Final: Tu plan de liderazgo personal', type: 'Reto', duration: '20 min', description: 'Quiz final del curso de liderazgo.', noteIntro: 'El quiz final evalúa todos los conceptos del curso.', notes: [], instructor: INSTRUCTORS.LF, resources: [] },
  ],

  'Marca personal digital': [
    { id: 1, title: '¿Qué es la marca personal y por qué importa?', type: 'Video', duration: '10:20', description: 'Entendé qué es la marca personal y cómo construirla de forma auténtica.', noteIntro: 'Tu marca personal existe aunque no la gestiones. La diferencia es si la controlás vos o la definen otros. En el mercado laboral actual, ser invisible es el mayor riesgo.', notes: [{ bold: 'Marca ≠ autopromoción:', text: ' Es comunicar tu valor de forma genuina para que los demás te encuentren y elijan.' }, { bold: 'Personal vs corporativa:', text: ' Las personas confían más en personas que en empresas. Tu marca amplifica la de tu empleador.' }, { bold: 'Consistencia:', text: ' LinkedIn, CV, entrevistas y referencias deben contar la misma historia.' }], instructor: INSTRUCTORS.AC, resources: [{ name: 'Guía de marca personal paso a paso', type: 'PDF', size: '1.1 MB' }] },
    { id: 2, title: 'Identificá tu propuesta de valor', type: 'Video', duration: '14:35', description: 'Cómo descubrir qué te hace único y articularlo de forma clara y memorable.', noteIntro: 'Tu propuesta de valor responde a: ¿Qué problema resolvés? ¿Para quién? ¿Mejor que quién? Articularlo claro es el corazón de tu marca.', notes: [{ bold: 'Ejercicio de los tres círculos:', text: ' Qué sos bueno haciendo + qué te apasiona + qué necesita el mercado. El centro es tu nicho.' }, { bold: 'Tus logros como evidencia:', text: ' No digas "soy organizado" — decí "implementé un sistema que redujo errores en un 40%".' }, { bold: 'El elevator pitch:', text: ' 30 segundos que comunican quién sos, qué hacés y qué buscás. Practicalo hasta que suene natural.' }], instructor: INSTRUCTORS.AC, resources: [{ name: 'Plantilla: Mi propuesta de valor', type: 'Doc', size: 'Google Docs' }, { name: 'Banco de logros cuantificados', type: 'PDF', size: '0.4 MB' }] },
    { id: 3, title: 'Optimizá tu perfil de LinkedIn', type: 'Video', duration: '18:40', description: 'Cada sección de LinkedIn optimizada para ser encontrado por recruiters.', noteIntro: 'LinkedIn es el buscador de talento más grande del mundo. Si tu perfil no aparece en las búsquedas, no existís para los recruiters.', notes: [{ bold: 'Foto y banner:', text: ' La foto genera la primera impresión en 0.1 segundos. El banner es tu valla publicitaria.' }, { bold: 'Titular profesional:', text: ' No copies tu cargo. Escribí tu propuesta de valor: quién sos + a quién ayudás + cómo.' }, { bold: 'Sección Acerca de:', text: ' En primera persona, contá tu historia, tus logros clave y qué tipo de oportunidades buscás.' }, { bold: 'Keywords estratégicas:', text: ' LinkedIn es un buscador. Las palabras clave en titular y resumen determinan si aparecer o no.' }], instructor: INSTRUCTORS.AC, resources: [{ name: 'Checklist de perfil LinkedIn All-Star', type: 'PDF', size: '0.8 MB' }, { name: 'Guía de keywords por industria', type: 'PDF', size: '1.1 MB' }] },
    { id: 4, title: 'Estrategia de contenido para profesionales', type: 'Video', duration: '22:10', description: 'Qué, cuándo y cómo publicar en LinkedIn para construir autoridad y visibilidad.', noteIntro: 'Publicar contenido en LinkedIn no es para influencers — es para profesionales que quieren ser referentes en su industria. El algoritmo premia la consistencia.', notes: [{ bold: 'Qué publicar:', text: ' Lecciones de tu experiencia, casos de estudio, opiniones sobre tendencias, aprendizajes de errores.' }, { bold: 'Frecuencia:', text: ' 2-3 veces por semana es suficiente para construir presencia. Calidad > cantidad.' }, { bold: 'Engagement genuino:', text: ' Comentar con profundidad en posts de referentes de tu industria genera más visibilidad que solo publicar.' }], instructor: INSTRUCTORS.AC, resources: [{ name: 'Calendario de contenido LinkedIn', type: 'Doc', size: 'Google Docs' }] },
    { id: 5, title: 'Reto Final: Tu perfil en 24hs', type: 'Reto', duration: '15 min', description: 'Quiz final del curso de marca personal digital.', noteIntro: 'Evaluación final: LinkedIn, marca personal y estrategia de contenido.', notes: [], instructor: INSTRUCTORS.AC, resources: [] },
  ],

  'Herramientas digitales modernas': [
    { id: 1, title: 'Ecosistema digital: panorama actual', type: 'Video', duration: '11:00', description: 'Mapa de las herramientas digitales más usadas en el trabajo moderno y cómo elegir las correctas.', noteIntro: 'Hoy existen miles de herramientas digitales. El desafío no es encontrar herramientas — es elegir las correctas y usarlas bien.', notes: [{ bold: 'Categorías clave:', text: ' Comunicación, productividad, almacenamiento, colaboración, gestión de proyectos y automatización.' }, { bold: 'Criterios de selección:', text: ' ¿Integra con lo que ya usás? ¿Tiene curva de aprendizaje razonable? ¿Escala con tu equipo?' }, { bold: 'Menos es más:', text: ' Usar 3 herramientas muy bien es mejor que usar 10 superficialmente.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Mapa de herramientas digitales 2025', type: 'PDF', size: '1.2 MB' }] },
    { id: 2, title: 'Google Workspace en profundidad', type: 'Video', duration: '16:20', description: 'Gmail, Drive, Docs, Sheets, Meet y Calendar: funciones avanzadas para ser más productivo.', noteIntro: 'Google Workspace es el ecosistema de productividad más usado en el mundo. Conocer sus funciones avanzadas ahorra horas de trabajo.', notes: [{ bold: 'Gmail con filtros y etiquetas:', text: ' Automatizá la organización de tu inbox. Reglas que procesan emails mientras dormís.' }, { bold: 'Google Docs colaborativo:', text: ' Comentarios, sugerencias, historial de versiones y edición simultánea en tiempo real.' }, { bold: 'Sheets con fórmulas clave:', text: ' BUSCARV, IMPORTRANGE, tablas dinámicas. Las fórmulas correctas reemplazan horas de trabajo manual.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Atajos de Google Workspace', type: 'PDF', size: '0.5 MB' }] },
    { id: 3, title: 'Microsoft 365 y OneDrive', type: 'Video', duration: '15:30', description: 'Word, Excel, PowerPoint y Teams en profundidad para entornos corporativos.', noteIntro: 'Microsoft 365 domina el entorno corporativo. Conocer sus capacidades colaborativas y de IA integrada es una ventaja competitiva.', notes: [{ bold: 'Excel avanzado:', text: ' Tablas dinámicas, Power Query, fórmulas dinámicas (XLOOKUP). Análisis de datos sin código.' }, { bold: 'PowerPoint con diseño profesional:', text: ' Plantillas, Smart Art, animaciones y narración de datos visualmente efectivos.' }, { bold: 'Copilot en M365:', text: ' IA integrada en Word, Excel y Teams que redacta, resume y analiza por vos.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía Excel avanzado', type: 'PDF', size: '1.4 MB' }] },
    { id: 4, title: 'Herramientas de colaboración: Teams y Slack', type: 'Video', duration: '14:00', description: 'Comunicación asíncrona y síncrona efectiva en equipos modernos.', noteIntro: 'La comunicación de equipo cambió. El email ya no alcanza — necesitás herramientas que combinen velocidad, organización y contexto.', notes: [{ bold: 'Canales vs DMs:', text: ' Los canales organizan por proyecto o tema; los DMs son para comunicación directa urgente.' }, { bold: 'Asincronismo inteligente:', text: ' No todo es urgente. Usar estados, threads y Loom reduce interrupciones y mejora el foco.' }, { bold: 'Integraciones:', text: ' Conectar Slack/Teams con Jira, GitHub, Google Drive y Calendar centraliza las notificaciones.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía de comunicación asíncrona', type: 'PDF', size: '0.7 MB' }] },
    { id: 5, title: 'Reto: Organización digital de tu trabajo', type: 'Reto', duration: '10 min', description: 'Quiz de herramientas digitales modernas.', noteIntro: 'Evaluación de Google Workspace, M365 y herramientas de colaboración.', notes: [], instructor: INSTRUCTORS.RS, resources: [] },
    { id: 6, title: 'Automatización sin código: Zapier y Make', type: 'Video', duration: '19:45', description: 'Creá flujos automáticos que conectan tus apps favoritas sin escribir código.', noteIntro: 'La automatización no es solo para programadores. Con herramientas no-code podés ahorrar horas de trabajo repetitivo y eliminar errores humanos.', notes: [{ bold: 'Zapier:', text: ' Disparadores + acciones en 5.000+ apps. Ej: "Cuando recibo email de un cliente → crear tarea en Asana".' }, { bold: 'Make (antes Integromat):', text: ' Más potente y visual que Zapier. Ideal para flujos complejos con condicionales y transformaciones.' }, { bold: 'Casos de uso frecuentes:', text: ' Sincronizar contactos, enviar notificaciones automáticas, generar reportes, actualizar hojas de cálculo.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Plantillas de automatización listas para usar', type: 'Doc', size: 'Google Docs' }] },
    { id: 7, title: 'Seguridad digital básica', type: 'Video', duration: '13:30', description: 'Contraseñas, 2FA, phishing y buenas prácticas para proteger tu información.', noteIntro: 'La seguridad digital no es solo responsabilidad del área de IT. Cada persona es un vector de riesgo o un escudo. Esta lección te da lo básico para estar protegido.', notes: [{ bold: 'Contraseñas seguras:', text: ' Usá un gestor (Bitwarden, 1Password). Una contraseña diferente y fuerte para cada servicio.' }, { bold: '2FA siempre:', text: ' El doble factor de autenticación bloquea el 99.9% de los ataques automatizados.' }, { bold: 'Phishing:', text: ' Verificá siempre el remitente real, los links antes de clickear y desconfiá de la urgencia artificial.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Checklist de seguridad digital', type: 'PDF', size: '0.4 MB' }] },
  ],

  'Gestión del cambio organizacional': [
    { id: 1, title: '¿Por qué fallan los procesos de cambio?', type: 'Video', duration: '13:00', description: 'Las razones más comunes por las que las transformaciones organizacionales no llegan a buen puerto.', noteIntro: 'El 70% de los procesos de cambio organizacional fracasan. No por falta de recursos o tecnología, sino por factores humanos y de gestión. Entender por qué es el primer paso.', notes: [{ bold: 'Subestimar la resistencia:', text: ' El cambio genera incertidumbre. Sin gestión proactiva, la resistencia natural se vuelve bloqueo activo.' }, { bold: 'Comunicación insuficiente:', text: ' En ausencia de información, las personas llenan los huecos con rumores y miedos.' }, { bold: 'Falta de victorias tempranas:', text: ' Los cambios largos sin resultados visibles pierden tracción. Las quick wins mantienen la energía.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Informe: Por qué fallan las transformaciones', type: 'PDF', size: '1.0 MB' }] },
    { id: 2, title: 'Modelo de Kotter: 8 pasos al cambio', type: 'Video', duration: '17:30', description: 'El framework de cambio más usado en el mundo explicado con casos reales.', noteIntro: 'John Kotter estudió cientos de cambios organizacionales y encontró que los exitosos siguen 8 pasos específicos. Este modelo sigue siendo el más aplicado 30 años después.', notes: [{ bold: 'Pasos 1-4 (preparar):', text: ' Crear urgencia → Coalición guía → Visión → Comunicar la visión.' }, { bold: 'Pasos 5-8 (ejecutar y sostener):', text: ' Eliminar obstáculos → Victorias tempranas → Consolidar → Anclar en cultura.' }, { bold: 'No es lineal:', text: ' En la práctica, los pasos se superponen y a veces hay que volver atrás. La flexibilidad es clave.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Poster: 8 pasos de Kotter', type: 'PDF', size: '0.6 MB' }] },
    { id: 3, title: 'La resistencia al cambio', type: 'Video', duration: '15:45', description: 'Por qué las personas resisten, cómo se manifiesta y cómo gestionarla constructivamente.', noteIntro: 'La resistencia no es mala. Es una señal de que las personas están involucradas y tienen preocupaciones legítimas. El error es ignorarla o aplastarla.', notes: [{ bold: 'Tipos de resistencia:', text: ' Activa (oposición directa), pasiva (falta de acción) y encubierta (sabotaje silencioso).' }, { bold: 'Causas profundas:', text: ' Miedo a perder estatus, poder, identidad o seguridad. Raramente es el cambio en sí.' }, { bold: 'Cómo gestionarla:', text: ' Escuchar sin juzgar, validar las preocupaciones, involucrar en el diseño del cambio.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía de gestión de resistencia', type: 'PDF', size: '0.8 MB' }] },
    { id: 4, title: 'Comunicación en el cambio', type: 'Video', duration: '16:20', description: 'Cómo diseñar una estrategia de comunicación que sostenga el cambio en cada etapa.', noteIntro: 'En un proceso de cambio, no podés comunicar demasiado. El silencio siempre se interpreta como malas noticias.', notes: [{ bold: 'El plan de comunicación:', text: ' Quién necesita saber qué, cuándo, por qué canal y con qué mensaje.' }, { bold: 'Frecuencia y consistencia:', text: ' Mensajes repetidos por múltiples canales y emisores refuerzan la credibilidad.' }, { bold: 'Bidireccional:', text: ' La comunicación del cambio no es solo transmitir — es también escuchar, responder y ajustar.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Plantilla de plan de comunicación', type: 'Doc', size: 'Google Docs' }] },
    { id: 5, title: 'Reto: Análisis de cambio en tu organización', type: 'Reto', duration: '15 min', description: 'Quiz de gestión del cambio organizacional.', noteIntro: 'Evaluación de Kotter, resistencia y comunicación del cambio.', notes: [], instructor: INSTRUCTORS.RS, resources: [] },
    { id: 6, title: 'Stakeholders y gestión de expectativas', type: 'Video', duration: '18:00', description: 'Cómo identificar, mapear y gestionar a todos los grupos de interés en un proceso de cambio.', noteIntro: 'No todos los stakeholders son iguales. Algunos pueden hundir el cambio; otros pueden impulsarlo. Mapearlos y gestionarlos estratégicamente es determinante.', notes: [{ bold: 'Matriz poder/interés:', text: ' Clasifica stakeholders por su poder de decisión y su interés en el cambio.' }, { bold: 'Aliados estratégicos:', text: ' Los líderes de opinión informales a veces tienen más influencia que los formales. Identificalos.' }, { bold: 'Gestión personalizada:', text: ' Cada stakeholder necesita un enfoque diferente. Un mensaje único no funciona para todos.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Plantilla de mapa de stakeholders', type: 'PDF', size: '0.5 MB' }] },
    { id: 7, title: 'Métricas y seguimiento del cambio', type: 'Video', duration: '14:30', description: 'Cómo medir el avance de un proceso de cambio y ajustar en tiempo real.', noteIntro: 'Lo que no se mide, no se gestiona. En los procesos de cambio, las métricas correctas permiten tomar decisiones basadas en evidencia y detectar problemas antes de que escalen.', notes: [{ bold: 'KPIs de adopción:', text: ' Porcentaje de usuarios activos, tareas migradas, procesos actualizados.' }, { bold: 'Pulso de clima:', text: ' Encuestas cortas y frecuentes (eNPS) para medir cómo está el equipo emocionalmente.' }, { bold: 'Leading vs lagging indicators:', text: ' Los leading (comportamientos actuales) predicen los lagging (resultados futuros).' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Dashboard de métricas de cambio', type: 'PDF', size: '0.9 MB' }] },
    { id: 8, title: 'Consolidación y cultura organizacional', type: 'Video', duration: '19:00', description: 'Cómo lograr que el cambio se quede y se convierta en parte de la cultura.', noteIntro: 'El cambio no termina cuando se implementa — termina cuando se convierte en la nueva normalidad. Esta fase es la más difícil y la más ignorada.', notes: [{ bold: 'Anclar en sistemas:', text: ' El cambio debe reflejarse en procesos, incentivos, métricas y estructuras formales.' }, { bold: 'Celebrar y reconocer:', text: ' Los comportamientos que se reconocen se repiten. Celebrá los avances públicamente.' }, { bold: 'Narrativa del cambio:', text: ' Construí una historia de éxito que refuerce por qué el cambio fue necesario y valió la pena.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía de consolidación del cambio', type: 'PDF', size: '0.7 MB' }] },
    { id: 9, title: 'Reto Final: Tu plan de cambio', type: 'Reto', duration: '20 min', description: 'Quiz final del curso de gestión del cambio organizacional.', noteIntro: 'Evaluación final completa de gestión del cambio.', notes: [], instructor: INSTRUCTORS.RS, resources: [] },
  ],

  'Comunicación efectiva': [
    { id: 1, title: 'Fundamentos de la comunicación profesional', type: 'Video', duration: '12:00', description: 'Modelo de comunicación, barreras más comunes y cómo superarlas.', noteIntro: 'La comunicación es la habilidad profesional más universal y menos entrenada. Mejorarla impacta directamente en tus relaciones, tu influencia y tus resultados.', notes: [{ bold: 'Emisor → canal → receptor:', text: ' El modelo básico esconde complejidades enormes. El contexto, el tono y el momento cambian todo.' }, { bold: 'Barreras frecuentes:', text: ' Ruido físico, diferencias culturales, emociones, asunciones y falta de claridad.' }, { bold: 'Comunicación clara:', text: ' Mensaje simple, específico y concreto. Si el receptor no entiende, el error siempre es del emisor.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Guía de comunicación efectiva', type: 'PDF', size: '0.9 MB' }] },
    { id: 2, title: 'Comunicación no verbal y presencia', type: 'Video', duration: '15:30', description: 'Lenguaje corporal, tono de voz y presencia ejecutiva.', noteIntro: 'El 93% de lo que comunicamos es no verbal (Mehrabian). Controlar tu lenguaje corporal no es manipulación — es alineación entre lo que pensás, sentís y transmitís.', notes: [{ bold: 'Postura de poder:', text: ' Espalda recta, contacto visual, gestos abiertos. Proyectan confianza y credibilidad.' }, { bold: 'Tono y velocidad:', text: ' Hablar pausado transmite seguridad. El tono ascendente al final de frase suena inseguro.' }, { bold: 'Mirroring:', text: ' Imitar sutilmente el lenguaje corporal de la otra persona genera rapport y confianza.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Checklist de lenguaje corporal', type: 'PDF', size: '0.4 MB' }] },
    { id: 3, title: 'Escucha activa y feedback constructivo', type: 'Video', duration: '18:00', description: 'Cómo escuchar de verdad y dar feedback que genere cambio real.', noteIntro: 'Escuchar es la habilidad de comunicación más importante y la menos practicada. La mayoría no escucha — espera su turno para hablar.', notes: [{ bold: 'Escucha activa:', text: ' Contacto visual, asentir, preguntas abiertas, parafrasear. Mostrá que estás presente.' }, { bold: 'Niveles de escucha:', text: ' Superficial (palabras) → comprensiva (significado) → empática (emoción). El nivel más profundo genera confianza.' }, { bold: 'Feedback SBI:', text: ' Situación específica + Comportamiento observable + Impacto concreto. Sin juicios ni generalizaciones.' }], instructor: INSTRUCTORS.LF, resources: [{ name: 'Plantilla de feedback SBI', type: 'Doc', size: 'Google Docs' }] },
    { id: 4, title: 'Reto Final: Tu comunicación en acción', type: 'Reto', duration: '15 min', description: 'Quiz final del curso de comunicación efectiva.', noteIntro: 'Evaluación final de comunicación verbal, no verbal y feedback.', notes: [], instructor: INSTRUCTORS.LF, resources: [] },
  ],

  'Pensamiento estratégico aplicado': [
    { id: 1, title: '¿Qué es pensar estratégicamente?', type: 'Video', duration: '13:20', description: 'Diferencia entre pensamiento táctico y estratégico, y cómo desarrollarlo.', noteIntro: 'El pensamiento estratégico es la capacidad de ver el bosque sin perder de vista los árboles. Es conectar el día a día con la visión de largo plazo.', notes: [{ bold: 'Táctico vs estratégico:', text: ' Táctico es "cómo". Estratégico es "por qué" y "hacia dónde". Necesitás ambos.' }, { bold: 'Pensamiento sistémico:', text: ' Ver las interconexiones, no los eventos aislados. Todo tiene causas y consecuencias no lineales.' }, { bold: 'Cómo desarrollarlo:', text: ' Reservar tiempo para pensar, leer fuera de tu industria, hacer preguntas de segundo orden.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Guía de pensamiento estratégico', type: 'PDF', size: '0.8 MB' }] },
    { id: 2, title: 'Análisis FODA profundo', type: 'Video', duration: '16:45', description: 'Cómo hacer un FODA que realmente sirva para tomar decisiones.', noteIntro: 'El FODA es la herramienta estratégica más conocida y peor usada. Un buen FODA no es una lista — es un análisis que lleva a decisiones concretas.', notes: [{ bold: 'Fortalezas reales:', text: ' No las que te gustaría tener. Las que son evidentes para clientes y competidores.' }, { bold: 'Oportunidades vs amenazas:', text: ' Son externas — no las controlás. Pero podés prepararte para aprovecharlas o mitigarlas.' }, { bold: 'FODA cruzado:', text: ' FO (fortalezas + oportunidades), FA, DO, DA. Aquí está la estrategia real.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Plantilla FODA cruzado', type: 'Doc', size: 'Google Docs' }] },
    { id: 3, title: 'Planificación estratégica práctica', type: 'Video', duration: '18:30', description: 'De la visión a los OKRs: cómo construir un plan que realmente se ejecute.', noteIntro: 'La mayoría de los planes estratégicos terminan en un cajón. Los que funcionan tienen en común claridad, métricas y responsables.', notes: [{ bold: 'Misión vs visión:', text: ' Misión es el propósito actual; visión es el destino futuro. Sin visión clara, no hay estrategia.' }, { bold: 'OKRs:', text: ' Objectives + Key Results. El sistema de metas de Google. Ambicioso, medible y alineado.' }, { bold: 'Revisión y ajuste:', text: ' Un plan estratégico que no se revisa mensualmente pierde vigencia. La estrategia es viva.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Plantilla de planificación con OKRs', type: 'Doc', size: 'Google Docs' }] },
    { id: 4, title: 'Reto: FODA personal y estrategia de carrera', type: 'Reto', duration: '15 min', description: 'Quiz de pensamiento estratégico aplicado.', noteIntro: 'Evaluación de FODA, planificación estratégica y OKRs.', notes: [], instructor: INSTRUCTORS.CM, resources: [] },
    { id: 5, title: 'Decisiones bajo incertidumbre', type: 'Video', duration: '17:00', description: 'Frameworks para decidir bien cuando los datos son incompletos o el contexto cambia rápido.', noteIntro: 'La incertidumbre no es excusa para no decidir — es el contexto normal del mundo de hoy. Los mejores estrategas aprenden a actuar con información imperfecta.', notes: [{ bold: 'Análisis de escenarios:', text: ' Planificá para el mejor, el peor y el más probable caso. No para predecir — para estar preparado.' }, { bold: 'Regla del 70%:', text: ' Si tenés el 70% de la información, decidí. Esperar el 100% significa llegar tarde.' }, { bold: 'Reversibilidad:', text: ' Distinguí decisiones reversibles (actuar rápido, aprender) de irreversibles (tomarse el tiempo).' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Framework de decisiones bajo incertidumbre', type: 'PDF', size: '0.6 MB' }] },
    { id: 6, title: 'Estrategia personal de carrera', type: 'Video', duration: '20:15', description: 'Aplicá el pensamiento estratégico a tu propia trayectoria profesional.', noteIntro: 'Tu carrera es el proyecto más importante que gestionás. Aplicarle pensamiento estratégico te da claridad, dirección y resiliencia ante los cambios del mercado.', notes: [{ bold: 'Tu ventaja competitiva:', text: ' Qué combinación única de habilidades, experiencia y red tenés que nadie más tiene exactamente igual.' }, { bold: 'Horizonte temporal:', text: ' Pensar en 3 horizontes: próximos 12 meses, 3-5 años y 10+ años. Cada uno requiere distintas acciones.' }, { bold: 'Gestión de red:', text: ' Tu red profesional no es lo que sabés — es quién sabe lo que sabés. Invertir en relaciones es estratégico.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Plantilla de plan de carrera', type: 'Doc', size: 'Google Docs' }] },
  ],

  'Productividad y enfoque digital': [
    { id: 1, title: 'Productividad vs estar ocupado', type: 'Video', duration: '11:30', description: 'La diferencia entre actividad y productividad, y cómo medir el trabajo que realmente importa.', noteIntro: 'Estar ocupado no es lo mismo que ser productivo. La trampa del siglo XXI es confundir cantidad de horas con valor generado.', notes: [{ bold: 'Actividad vs resultado:', text: ' El trabajo que importa es el que avanza objetivos reales. Todo lo demás es ruido.' }, { bold: 'La trampa del email:', text: ' El email da sensación de productividad. Gestionar inbox no es trabajar — es prepararse para trabajar.' }, { bold: 'Deep Work:', text: ' Bloques de 90-120 minutos de trabajo sin interrupciones. Es donde se produce el trabajo de más valor.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Resumen: Deep Work (Cal Newport)', type: 'PDF', size: '0.5 MB' }] },
    { id: 2, title: 'Técnica Pomodoro y gestión del tiempo', type: 'Video', duration: '14:20', description: 'Sistema de bloques de tiempo para maximizar el foco y evitar la fatiga mental.', noteIntro: 'La técnica Pomodoro es simple pero poderosa: 25 minutos de foco total + 5 de descanso. Repetido, convierte la jornada en sprints de alta productividad.', notes: [{ bold: 'El ciclo básico:', text: ' 25 min trabajo → 5 min descanso → cada 4 ciclos, descanso largo de 15-30 min.' }, { bold: 'Por qué funciona:', text: ' Crea urgencia artificial (25 min no es mucho) y los descansos previenen la fatiga cognitiva.' }, { bold: 'Adaptalo:', text: ' Algunos prefieren ciclos de 50/10. Lo importante es la alternancia trabajo-descanso intencional.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía completa Pomodoro', type: 'PDF', size: '0.4 MB' }] },
    { id: 3, title: 'Organización digital: inbox cero y GTD', type: 'Video', duration: '17:45', description: 'Cómo organizar tu trabajo digital para que nada se pierda y siempre sepás qué hacer.', noteIntro: 'GTD (Getting Things Done) de David Allen es el sistema de productividad más influyente de los últimos 20 años. Inbox cero no es una obsesión — es un sistema.', notes: [{ bold: 'Los 5 pasos del GTD:', text: ' Capturar → Procesar → Organizar → Revisar → Ejecutar. Un sistema confiable vacía la mente.' }, { bold: 'Inbox cero:', text: ' El inbox es una bandeja de entrada, no un archivo. Cada email: eliminar, delegar, responder o archivar.' }, { bold: 'Herramientas recomendadas:', text: ' Notion, Todoist o Things para tareas. Un sistema de archivos digital limpio y consistente.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Resumen GTD aplicado', type: 'PDF', size: '0.8 MB' }, { name: 'Plantilla de sistema GTD en Notion', type: 'Doc', size: 'Notion' }] },
    { id: 4, title: 'Reto: Tu sistema de productividad', type: 'Reto', duration: '10 min', description: 'Quiz de productividad personal y enfoque digital.', noteIntro: 'Evaluación de Pomodoro, GTD y gestión del tiempo.', notes: [], instructor: INSTRUCTORS.RS, resources: [] },
    { id: 5, title: 'Hábitos digitales saludables', type: 'Video', duration: '16:00', description: 'Cómo relacionarte con la tecnología de forma intencional y evitar el agotamiento digital.', noteIntro: 'La tecnología puede ser tu mayor aliada o tu mayor distracción. La diferencia la hace la intencionalidad con la que la usás.', notes: [{ bold: 'Higiene digital:', text: ' Notificaciones en silencio, apps organizadas, tiempo de pantalla controlado. Vos controlás la tecnología.' }, { bold: 'Separar trabajo de descanso:', text: ' El trabajo remoto borra los límites. Rituales de inicio y cierre de jornada mantienen el equilibrio.' }, { bold: 'Desconexión intencional:', text: ' Tiempo sin pantallas es tiempo de recuperación cognitiva. No es pérdida de productividad — es su fundamento.' }], instructor: INSTRUCTORS.RS, resources: [{ name: 'Guía de hábitos digitales saludables', type: 'PDF', size: '0.6 MB' }] },
  ],

  'Transformación digital en empresas': [
    { id: 1, title: 'Qué es (y qué no es) transformación digital', type: 'Video', duration: '14:00', description: 'Aclarando conceptos: diferencia entre digitalización, automatización y transformación digital real.', noteIntro: 'Transformación digital es el término más usado y peor entendido del management actual. Antes de implementar, hay que entender exactamente de qué se trata.', notes: [{ bold: 'Digitalización:', text: ' Convertir un proceso manual a digital. Ej: factura papel → PDF. Necesario pero no suficiente.' }, { bold: 'Transformación digital:', text: ' Reimaginar el modelo de negocio aprovechando capacidades digitales. Es estrategia, no tecnología.' }, { bold: 'El error más común:', text: ' Comprar tecnología sin cambiar procesos ni cultura. La tecnología sin cambio humano es desperdicio.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Glosario de transformación digital', type: 'PDF', size: '0.5 MB' }] },
    { id: 2, title: 'Diagnóstico digital de tu empresa', type: 'Video', duration: '16:30', description: 'Cómo evaluar la madurez digital de tu organización y detectar brechas.', noteIntro: 'Antes de transformar, hay que saber desde dónde. El diagnóstico digital es el punto de partida de cualquier transformación seria.', notes: [{ bold: 'Modelo de madurez digital:', text: ' 5 niveles: Inicial → Desarrollado → Definido → Gestionado → Optimizado. ¿Dónde está tu empresa?' }, { bold: 'Dimensiones a evaluar:', text: ' Estrategia, cultura, procesos, tecnología, datos y talento.' }, { bold: 'Quick wins vs transformación:', text: ' Identificar victorias rápidas que financien el camino largo de la transformación profunda.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Cuestionario de madurez digital', type: 'PDF', size: '0.7 MB' }] },
    { id: 3, title: 'Tecnologías habilitadoras', type: 'Video', duration: '18:45', description: 'IA, cloud, IoT, blockchain y automatización: qué son, para qué sirven y cuándo usarlas.', noteIntro: 'No necesitás usar todas las tecnologías disponibles — necesitás elegir las correctas para el problema correcto. Esta lección te da el mapa.', notes: [{ bold: 'Cloud computing:', text: ' La base de la transformación. Escalabilidad, costos variables, acceso desde cualquier lugar.' }, { bold: 'IA y Analytics:', text: ' Convertir datos en decisiones. Desde análisis descriptivo hasta IA generativa.' }, { bold: 'Automatización de procesos (RPA):', text: ' Robots de software que ejecutan tareas repetitivas. ROI rápido y medible.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Mapa de tecnologías habilitadoras', type: 'PDF', size: '1.3 MB' }] },
    { id: 4, title: 'El rol de las personas en la transformación', type: 'Video', duration: '17:20', description: 'Por qué las transformaciones fallan por factores humanos y cómo liderarlas con éxito.', noteIntro: 'La transformación digital es 20% tecnología y 80% personas. Las empresas que lo entienden son las que logran transformaciones duraderas.', notes: [{ bold: 'Cultura digital:', text: ' Apertura al cambio, tolerancia al error, colaboración cross-funcional y orientación a datos.' }, { bold: 'Upskilling y reskilling:', text: ' Invertir en el desarrollo digital del equipo existente es más efectivo que contratar externamente.' }, { bold: 'Liderazgo del cambio:', text: ' Los líderes deben ser los primeros en adoptar y modelar los nuevos comportamientos.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Guía de cultura digital', type: 'PDF', size: '0.9 MB' }] },
    { id: 5, title: 'Reto: Mapa de transformación digital', type: 'Reto', duration: '15 min', description: 'Quiz de transformación digital en empresas.', noteIntro: 'Evaluación de conceptos, tecnologías y gestión del cambio digital.', notes: [], instructor: INSTRUCTORS.CM, resources: [] },
    { id: 6, title: 'Casos de éxito y lecciones aprendidas', type: 'Video', duration: '21:00', description: 'Análisis de transformaciones digitales exitosas y qué hicieron diferente.', noteIntro: 'Aprender de los que ya lo hicieron bien (y mal) acelera tu curva. Esta lección analiza casos reales con lecciones concretas aplicables.', notes: [{ bold: 'Amazon:', text: ' La obsesión por el cliente y la cultura de experimentación constante como motores de transformación.' }, { bold: 'BBVA:', text: ' De banco tradicional a empresa de software que tiene licencia bancaria. Una transformación total.' }, { bold: 'Pymes exitosas:', text: ' La escala pequeña es una ventaja — permite pivotar rápido. Los casos de pymes son los más aplicables para la mayoría.' }], instructor: INSTRUCTORS.CM, resources: [{ name: 'Casos de estudio: transformación digital', type: 'PDF', size: '2.2 MB' }] },
  ],

  'Innovación y creatividad': [
    { id: 1, title: 'Mitos de la creatividad y cómo superarlos', type: 'Video', duration: '10:30', description: 'Desmontando las creencias que bloquean la creatividad y cómo activarla en el trabajo.', noteIntro: 'Todos nacemos creativos. Lo que ocurre es que el sistema educativo y el trabajo rutinario lo van apagando. Esta lección es sobre cómo volver a encenderlo.', notes: [{ bold: 'Mito 1: "Soy o no soy creativo":', text: ' La creatividad es una habilidad que se entrena, no un talento innato que se tiene o no.' }, { bold: 'Mito 2: "La creatividad es para artistas":', text: ' Resolver problemas, mejorar procesos y generar ideas nuevas son actos creativos cotidianos.' }, { bold: 'Cómo activarla:', text: ' Cambio de entorno, estímulos nuevos, tiempo de incubación y permiso para generar ideas malas.' }], instructor: INSTRUCTORS.MT, resources: [{ name: 'Guía de creatividad aplicada al trabajo', type: 'PDF', size: '0.7 MB' }] },
    { id: 2, title: 'Design Thinking paso a paso', type: 'Video', duration: '18:20', description: 'El proceso de innovación centrada en el usuario: empatizar, definir, idear, prototipar y testear.', noteIntro: 'Design Thinking no es solo para diseñadores. Es una mentalidad para resolver problemas complejos poniendo al usuario en el centro. Usado por IDEO, Apple y miles de empresas innovadoras.', notes: [{ bold: 'Empatizar:', text: ' Observar, entrevistar y ponerse en los zapatos del usuario. Entender el problema real, no el percibido.' }, { bold: 'Definir e Idear:', text: ' Reformular el problema con los insights del usuario y generar decenas de ideas sin juzgar.' }, { bold: 'Prototipar y Testear:', text: ' Hacer algo tangible rápido y barato para aprender del usuario real. El prototipo es una pregunta, no una respuesta.' }], instructor: INSTRUCTORS.MT, resources: [{ name: 'Canvas de Design Thinking', type: 'PDF', size: '0.6 MB' }, { name: 'Guía de entrevistas de usuario', type: 'PDF', size: '0.4 MB' }] },
    { id: 3, title: 'Técnicas de ideación y creatividad grupal', type: 'Video', duration: '15:45', description: 'Brainstorming, SCAMPER, mapas mentales y otras técnicas para generar ideas en equipo.', noteIntro: 'La ideación efectiva no es espontánea — tiene estructura. Las técnicas correctas multiplican la cantidad y calidad de ideas que genera un equipo.', notes: [{ bold: 'Brainstorming efectivo:', text: ' Separar divergencia (generar) de convergencia (evaluar). Nunca juzgar ideas durante la generación.' }, { bold: 'SCAMPER:', text: ' Sustituir, Combinar, Adaptar, Modificar, Proponer otros usos, Eliminar, Reorganizar. 7 lentes de innovación.' }, { bold: 'Mapas mentales:', text: ' Partir de una idea central y ramificar asociaciones. Excelente para estructurar pensamiento complejo.' }], instructor: INSTRUCTORS.MT, resources: [{ name: 'Guía de técnicas de ideación', type: 'PDF', size: '0.8 MB' }] },
    { id: 4, title: 'Reto Final: Tu MVP de innovación', type: 'Reto', duration: '20 min', description: 'Quiz final del curso de innovación y creatividad.', noteIntro: 'Evaluación final: creatividad, Design Thinking y técnicas de ideación.', notes: [], instructor: INSTRUCTORS.MT, resources: [] },
  ],
};

/* ─────────────── SEED DATA ─────────────── */
const SEED_COURSES = [
  { title: 'Fundamentos de Inteligencia Artificial', description: 'Aprende los conceptos básicos de IA aplicados al trabajo.', level: 'Básico', duration: '3h 20m', modulesCount: 6, skills: ['IA básica', 'Pensamiento digital', 'Automatización'], emoji: '🤖' },
  { title: 'Liderazgo en entornos cambiantes', description: 'Desarrolla habilidades de liderazgo moderno.', level: 'Avanzado', duration: '5h 10m', modulesCount: 8, skills: ['Liderazgo', 'Gestión del cambio', 'Comunicación'], emoji: '🌟' },
  { title: 'Marca personal digital', description: 'Construye una presencia profesional sólida online.', level: 'Intermedio', duration: '2h 45m', modulesCount: 5, skills: ['Marca personal', 'LinkedIn', 'Networking'], emoji: '🔗' },
  { title: 'Herramientas digitales modernas', description: 'Domina herramientas digitales clave para el trabajo.', level: 'Básico', duration: '4h 00m', modulesCount: 7, skills: ['Office', 'Google Suite', 'Productividad'], emoji: '📊' },
  { title: 'Gestión del cambio organizacional', description: 'Aprende a liderar procesos de transformación.', level: 'Avanzado', duration: '6h 15m', modulesCount: 9, skills: ['Cambio', 'Estrategia', 'Liderazgo'], emoji: '🔄' },
  { title: 'Comunicación efectiva', description: 'Mejora tu comunicación en entornos profesionales.', level: 'Intermedio', duration: '2h 30m', modulesCount: 4, skills: ['Comunicación', 'Soft skills'], emoji: '💬' },
  { title: 'Pensamiento estratégico aplicado', description: 'Aprende a tomar decisiones con visión de negocio.', level: 'Avanzado', duration: '4h 50m', modulesCount: 6, skills: ['Estrategia', 'Análisis', 'Decisiones'], emoji: '♟️' },
  { title: 'Productividad y enfoque digital', description: 'Mejora tu rendimiento con técnicas modernas de productividad.', level: 'Básico', duration: '2h 40m', modulesCount: 5, skills: ['Productividad', 'Organización', 'Hábitos'], emoji: '⚡' },
  { title: 'Transformación digital en empresas', description: 'Entiende cómo las empresas evolucionan digitalmente.', level: 'Intermedio', duration: '3h 10m', modulesCount: 6, skills: ['Transformación', 'Digitalización', 'Estrategia'], emoji: '🏢' },
  { title: 'Innovación y creatividad', description: 'Desarrolla pensamiento creativo aplicado al trabajo.', level: 'Básico', duration: '2h 20m', modulesCount: 4, skills: ['Creatividad', 'Innovación'], emoji: '💡' },
];

const SEED_QUIZZES: Record<string, any> = {
  'Fundamentos de Inteligencia Artificial': { title: 'Quiz: IA Aplicada', isFinal: false, xpReward: 80, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Qué es el Machine Learning?', options: [{ id: 'a', text: 'Un tipo de hardware' }, { id: 'b', text: 'Un algoritmo que aprende de datos' }, { id: 'c', text: 'Un lenguaje de programación' }, { id: 'd', text: 'Un sistema operativo' }], correctId: 'b', explanation: 'Machine Learning es una rama de la IA donde los sistemas aprenden patrones a partir de datos sin ser explícitamente programados.' }, { id: 2, type: 'truefalse', question: 'La IA puede reemplazar completamente el juicio humano en decisiones éticas complejas.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'La IA es una herramienta poderosa, pero las decisiones éticas complejas requieren criterio humano.' }, { id: 3, type: 'multiple', question: '¿Cuál es una aplicación práctica de la IA en el trabajo diario?', options: [{ id: 'a', text: 'Automatizar respuestas de email repetitivas' }, { id: 'b', text: 'Reemplazar reuniones de equipo' }, { id: 'c', text: 'Eliminar la necesidad de planificación' }, { id: 'd', text: 'Gestionar recursos humanos sin intervención' }], correctId: 'a', explanation: 'La IA puede automatizar tareas repetitivas como clasificar emails o generar respuestas estándar.' }] },
  'Liderazgo en entornos cambiantes': { title: 'Quiz: Liderazgo Moderno', isFinal: false, xpReward: 100, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Qué caracteriza a un líder adaptativo?', options: [{ id: 'a', text: 'Mantiene siempre el mismo estilo de gestión' }, { id: 'b', text: 'Evita los conflictos a toda costa' }, { id: 'c', text: 'Ajusta su enfoque según el contexto y las necesidades del equipo' }, { id: 'd', text: 'Toma todas las decisiones de forma individual' }], correctId: 'c', explanation: 'El liderazgo adaptativo implica leer el contexto y ajustar el estilo según las circunstancias.' }, { id: 2, type: 'truefalse', question: 'La inteligencia emocional es más importante que la inteligencia técnica en roles de liderazgo.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'true', explanation: 'La IE es el factor diferenciador más importante en líderes efectivos a largo plazo.' }, { id: 3, type: 'multiple', question: '¿Qué es la "gestión del cambio"?', options: [{ id: 'a', text: 'Resistir transformaciones en la organización' }, { id: 'b', text: 'Proceso estructurado para transitar de un estado actual a uno deseado' }, { id: 'c', text: 'Cambiar de líder cuando hay problemas' }, { id: 'd', text: 'Actualizar el software de la empresa' }], correctId: 'b', explanation: 'La gestión del cambio involucra planificación, comunicación y seguimiento para lograr transformaciones efectivas.' }] },
  'Marca personal digital': { title: 'Quiz: Presencia Digital', isFinal: false, xpReward: 80, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Cuál es el elemento MÁS importante para que un recruiter te encuentre en LinkedIn?', options: [{ id: 'a', text: 'Tener más de 500 conexiones' }, { id: 'b', text: 'Usar palabras clave de tu industria en el titular y resumen' }, { id: 'c', text: 'Publicar contenido todos los días' }, { id: 'd', text: 'Tener foto de perfil profesional' }], correctId: 'b', explanation: 'LinkedIn funciona como un buscador. Las keywords en el titular son los campos con mayor peso.' }, { id: 2, type: 'truefalse', question: 'El titular de LinkedIn debe mostrar solo tu último cargo y empresa.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'El titular es tu propuesta de valor. Debe comunicar quién sos, a quién ayudás y qué problema resolvés.' }, { id: 3, type: 'multiple', question: '¿Qué significa tener un perfil de LinkedIn con "All-Star Status"?', options: [{ id: 'a', text: 'Tenés más de 1000 seguidores' }, { id: 'b', text: 'Completaste todas las secciones clave del perfil' }, { id: 'c', text: 'Publicaste más de 50 artículos' }, { id: 'd', text: 'LinkedIn te verificó como experto en tu industria' }], correctId: 'b', explanation: 'All-Star es el nivel máximo de completitud que da mayor visibilidad en búsquedas.' }] },
  'Herramientas digitales modernas': { title: 'Quiz: Herramientas Digitales', isFinal: false, xpReward: 70, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Cuál es la principal ventaja de Google Drive?', options: [{ id: 'a', text: 'Mayor velocidad de procesamiento' }, { id: 'b', text: 'Acceso desde cualquier dispositivo y colaboración en tiempo real' }, { id: 'c', text: 'Mayor capacidad de almacenamiento gratuita' }, { id: 'd', text: 'No requiere conexión a internet' }], correctId: 'b', explanation: 'La nube permite acceder desde cualquier dispositivo y colaborar simultáneamente.' }, { id: 2, type: 'truefalse', question: 'Microsoft Teams y Slack tienen funciones muy similares para la comunicación de equipos.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'true', explanation: 'Ambas plataformas ofrecen mensajería, videollamadas y canales temáticos.' }, { id: 3, type: 'multiple', question: '¿Qué es una tabla dinámica en Excel/Sheets?', options: [{ id: 'a', text: 'Una hoja que cambia de color automáticamente' }, { id: 'b', text: 'Una tabla que resume y agrupa datos automáticamente' }, { id: 'c', text: 'Un documento que se imprime solo' }, { id: 'd', text: 'Una fórmula que calcula en tiempo real' }], correctId: 'b', explanation: 'Las tablas dinámicas permiten resumir, agrupar y analizar grandes volúmenes de datos fácilmente.' }] },
  'Gestión del cambio organizacional': { title: 'Quiz: Transformación Organizacional', isFinal: false, xpReward: 100, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Cuál es el primer paso del modelo de Kotter?', options: [{ id: 'a', text: 'Crear una visión para el cambio' }, { id: 'b', text: 'Celebrar los logros' }, { id: 'c', text: 'Crear urgencia' }, { id: 'd', text: 'Formar un equipo líder' }], correctId: 'c', explanation: 'Kotter establece que el primer paso es crear un sentido de urgencia.' }, { id: 2, type: 'truefalse', question: 'La resistencia al cambio siempre es negativa y debe eliminarse.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'La resistencia puede ser una señal valiosa de problemas legítimos.' }, { id: 3, type: 'multiple', question: '¿Qué es la "consolidación de cambios"?', options: [{ id: 'a', text: 'Volver a las prácticas anteriores' }, { id: 'b', text: 'Asegurarse de que los nuevos comportamientos se conviertan en cultura' }, { id: 'c', text: 'Documentar todos los cambios realizados' }, { id: 'd', text: 'Contratar nuevos líderes' }], correctId: 'b', explanation: 'La consolidación integra los cambios en cultura organizacional para que persistan.' }] },
  'Comunicación efectiva': { title: 'Quiz: Comunicación Profesional', isFinal: false, xpReward: 70, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Qué porcentaje de la comunicación es no verbal (Mehrabian)?', options: [{ id: 'a', text: '20%' }, { id: 'b', text: '50%' }, { id: 'c', text: '93%' }, { id: 'd', text: '38%' }], correctId: 'c', explanation: 'El 55% es lenguaje corporal, 38% tono de voz y solo 7% palabras.' }, { id: 2, type: 'truefalse', question: 'La escucha activa implica solo prestar atención a las palabras de quien habla.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'La escucha activa incluye atención al lenguaje no verbal, validación emocional y preguntas abiertas.' }, { id: 3, type: 'multiple', question: '¿Cuál es la estructura más efectiva para dar feedback?', options: [{ id: 'a', text: 'Mencionar solo lo negativo' }, { id: 'b', text: 'Situación → Comportamiento → Impacto' }, { id: 'c', text: 'Empezar siempre con un cumplido' }, { id: 'd', text: 'Enviar el feedback por escrito siempre' }], correctId: 'b', explanation: 'El modelo SBI es el más efectivo: describe situación, comportamiento e impacto sin juicios.' }] },
  'Pensamiento estratégico aplicado': { title: 'Quiz: Estrategia y Decisiones', isFinal: false, xpReward: 90, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Qué analiza un FODA/SWOT?', options: [{ id: 'a', text: 'Finanzas, Operaciones, Datos y Automatización' }, { id: 'b', text: 'Fortalezas, Oportunidades, Debilidades y Amenazas' }, { id: 'c', text: 'Funciones, Objetivos, Workflow y Tareas' }, { id: 'd', text: 'Factores, Operaciones, Demanda y Activos' }], correctId: 'b', explanation: 'El FODA evalúa factores internos (Fortalezas/Debilidades) y externos (Oportunidades/Amenazas).' }, { id: 2, type: 'truefalse', question: 'La planificación estratégica solo es útil para grandes empresas.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'El pensamiento estratégico es valioso a cualquier escala.' }, { id: 3, type: 'multiple', question: '¿Qué es una decisión "data-driven"?', options: [{ id: 'a', text: 'Una decisión tomada rápidamente' }, { id: 'b', text: 'Una decisión basada en intuición' }, { id: 'c', text: 'Una decisión fundamentada en análisis de datos concretos' }, { id: 'd', text: 'Una decisión delegada al equipo de datos' }], correctId: 'c', explanation: 'Las decisiones basadas en datos combinan métricas y análisis con el juicio del tomador.' }] },
  'Productividad y enfoque digital': { title: 'Quiz: Productividad Personal', isFinal: false, xpReward: 70, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿En qué consiste la técnica Pomodoro?', options: [{ id: 'a', text: 'Trabajar 2 horas continuas sin interrupciones' }, { id: 'b', text: 'Alternar bloques de 25 minutos de trabajo con 5 de descanso' }, { id: 'c', text: 'Planificar el día con 3 tareas prioritarias' }, { id: 'd', text: 'Trabajar solo por las mañanas' }], correctId: 'b', explanation: 'El método Pomodoro usa ciclos de 25 minutos de trabajo seguidos de 5 de descanso.' }, { id: 2, type: 'truefalse', question: 'El multitasking aumenta la productividad.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'El cerebro no procesa simultáneamente — alterna tareas con un costo cognitivo cada vez.' }, { id: 3, type: 'multiple', question: '¿Qué es la "matriz de Eisenhower"?', options: [{ id: 'a', text: 'Una herramienta para priorizar tareas según urgencia e importancia' }, { id: 'b', text: 'Un método para gestionar reuniones' }, { id: 'c', text: 'Un sistema de archivos digitales' }, { id: 'd', text: 'Una técnica de respiración' }], correctId: 'a', explanation: 'La matriz clasifica tareas en 4 cuadrantes según urgencia e importancia.' }] },
  'Transformación digital en empresas': { title: 'Quiz: Digitalización Empresarial', isFinal: false, xpReward: 80, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Cuál es la diferencia entre digitalización y transformación digital?', options: [{ id: 'a', text: 'Son exactamente lo mismo' }, { id: 'b', text: 'Digitalización convierte procesos a digital; transformación cambia el modelo de negocio' }, { id: 'c', text: 'Transformación es solo para startups' }, { id: 'd', text: 'Digitalización requiere más inversión' }], correctId: 'b', explanation: 'Digitalizar es pasar un proceso manual a digital. Transformar es reimaginar el negocio completo.' }, { id: 2, type: 'truefalse', question: 'La transformación digital es principalmente un proyecto de tecnología.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'La transformación digital es 80% cambio cultural y 20% tecnología.' }, { id: 3, type: 'multiple', question: '¿Qué es la "experiencia del cliente digital"?', options: [{ id: 'a', text: 'Tener una página web' }, { id: 'b', text: 'La suma de interacciones que un cliente tiene a través de canales digitales' }, { id: 'c', text: 'Un programa de fidelización online' }, { id: 'd', text: 'El soporte técnico por chat' }], correctId: 'b', explanation: 'La CX digital abarca web, app, redes sociales, email y más.' }] },
  'Innovación y creatividad': { title: 'Quiz: Creatividad Aplicada', isFinal: false, xpReward: 70, passingScore: 70, questions: [{ id: 1, type: 'multiple', question: '¿Qué es el Design Thinking?', options: [{ id: 'a', text: 'Un software de diseño gráfico' }, { id: 'b', text: 'Una metodología de innovación centrada en las personas' }, { id: 'c', text: 'Un tipo de pensamiento matemático' }, { id: 'd', text: 'Una técnica de presentación visual' }], correctId: 'b', explanation: 'Design Thinking es un proceso de 5 fases para resolver problemas complejos centrado en el usuario.' }, { id: 2, type: 'truefalse', question: 'La creatividad es una habilidad innata que no se puede desarrollar.', options: [{ id: 'true', text: 'Verdadero' }, { id: 'false', text: 'Falso' }], correctId: 'false', explanation: 'La creatividad es una habilidad que se entrena con técnicas y práctica.' }, { id: 3, type: 'multiple', question: '¿Qué es un MVP en innovación?', options: [{ id: 'a', text: 'El empleado más valioso del equipo' }, { id: 'b', text: 'Mínimo Producto Viable para validar una idea rápidamente' }, { id: 'c', text: 'Un plan de marketing preliminar' }, { id: 'd', text: 'Una reunión de validación con stakeholders' }], correctId: 'b', explanation: 'El MVP es la versión más simple de un producto que permite aprender del mercado real.' }] },
};

@Injectable()
export class LearningService implements OnApplicationBootstrap {
  constructor(
    @InjectRepository(CourseOrmEntity)
    private readonly courseRepo: Repository<CourseOrmEntity>,
    @InjectRepository(UserProgressOrmEntity)
    private readonly progressRepo: Repository<UserProgressOrmEntity>,
    @InjectRepository(QuizResultOrmEntity)
    private readonly quizResultRepo: Repository<QuizResultOrmEntity>,
  ) {}

  async onApplicationBootstrap() {
    const count = await this.courseRepo.count();
    if (count === 0) {
      const courses = SEED_COURSES.map(c => this.courseRepo.create({ id: uuidv4(), ...c }));
      await this.courseRepo.save(courses);
    }
    await this.ensureQuizzes();
    await this.ensureLessons();
  }

  private async ensureQuizzes() {
    const courses = await this.courseRepo.find();
    const updates = courses.filter(c => !c.quiz).map(c => {
      const quiz = SEED_QUIZZES[c.title];
      return quiz ? this.courseRepo.save({ ...c, quiz }) : null;
    }).filter(Boolean);
    if (updates.length) await Promise.all(updates);
  }

  private async ensureLessons() {
    const courses = await this.courseRepo.find();
    const updates = courses.filter(c => !c.lessons).map(c => {
      const lessons = COURSE_LESSONS[c.title];
      return lessons ? this.courseRepo.save({ ...c, lessons }) : null;
    }).filter(Boolean);
    if (updates.length) await Promise.all(updates);
  }

  async getCourses() {
    return this.courseRepo.find({ order: { createdAt: 'ASC' } });
  }

  async getCourse(id: string) {
    const course = await this.courseRepo.findOneBy({ id });
    if (!course) throw new NotFoundException('Curso no encontrado');
    return course;
  }

  async getQuiz(courseId: string) {
    const course = await this.courseRepo.findOneBy({ id: courseId });
    if (!course) throw new NotFoundException('Curso no encontrado');
    if (!course.quiz) throw new NotFoundException('Este curso no tiene quiz disponible');
    return course.quiz;
  }

  async getUserProgress(userId: string) {
    return this.progressRepo.find({ where: { userId }, relations: ['course'] });
  }

  async completeLesson(userId: string, courseId: string, lessonIndex: number) {
    const course = await this.courseRepo.findOneBy({ id: courseId });
    if (!course) throw new NotFoundException('Curso no encontrado');

    let record = await this.progressRepo.findOneBy({ userId, courseId });
    if (!record) {
      record = this.progressRepo.create({ id: uuidv4(), userId, courseId, progress: 0, completedLessons: [] });
    }

    if (!record.completedLessons.includes(lessonIndex)) {
      record.completedLessons = [...record.completedLessons, lessonIndex];
    }

    const totalLessons = (course.lessons ?? []).length || 1;
    record.progress = Math.round((record.completedLessons.length / totalLessons) * 100);

    return this.progressRepo.save(record);
  }

  async updateProgress(userId: string, courseId: string, dto: UpdateProgressDto) {
    let record = await this.progressRepo.findOneBy({ userId, courseId });
    if (!record) {
      const course = await this.courseRepo.findOneBy({ id: courseId });
      if (!course) throw new NotFoundException('Curso no encontrado');
      record = this.progressRepo.create({ id: uuidv4(), userId, courseId, progress: 0, completedLessons: [] });
    }
    record.progress = dto.progress;
    return this.progressRepo.save(record);
  }

  async getCoursesWithProgress(userId: string) {
    const [courses, progressList] = await Promise.all([this.getCourses(), this.getUserProgress(userId)]);
    const progressMap = new Map(progressList.map(p => [p.courseId, p]));
    return courses.map(c => {
      const prog = progressMap.get(c.id);
      return { ...c, progress: prog?.progress ?? 0, completedLessons: prog?.completedLessons ?? [] };
    });
  }

  async saveQuizResult(userId: string, courseId: string, score: number, passed: boolean, correctCount: number, totalQuestions: number) {
    const course = await this.courseRepo.findOneBy({ id: courseId });
    if (!course) throw new NotFoundException('Curso no encontrado');

    const result = this.quizResultRepo.create({
      id: uuidv4(),
      userId,
      courseId,
      score,
      passed,
      correctCount,
      totalQuestions,
    });
    return this.quizResultRepo.save(result);
  }

  async getMyQuizResults(userId: string) {
    return this.quizResultRepo.find({
      where: { userId },
      relations: ['course'],
      order: { createdAt: 'DESC' },
    });
  }
}
